misc(sidekiq): Add sidekiq events worker
getlago/lago-api pull request #1368
Opened 2023-10-04 13:07 UTC by jdenquin

- Add a separated worker config for events

2023-10-04 13:09 UTC, jdenquin commented on app/jobs/events/create_job.rb
> +        :events
Layout/TrailingWhitespace: Trailing whitespace detected. (https://rubystyle.guide#no-trailing-whitespace)

2023-10-05 07:24 UTC, vincent-pochet approved these changes

2023-10-05 07:24 UTC, vincent-pochet commented on app/jobs/events/create_job.rb
> +      if ENV['SIDEKIQ_EVENTS'].present? && ENV['SIDEKIQ_EVENTS'] == 'true'
You can go with `ActiveModel::Type::Boolean.new.cast(ENV['SIDEKIQ_EVENTS'])`

2023-10-05 11:15 UTC, ivannovosad requested changes

2023-10-05 11:15 UTC, ivannovosad commented on scripts/start.events.worker.sh
> +bundle exec sidekiq -C config/sidekiq_events.yml
Lets add a newline at the end of the file.

2023-10-05 14:40 UTC, ivannovosad approved these changes

2023-10-05 14:43 UTC, merged